### ISSUE TITLE
8つ目以降の髪型を使用したキャラクターで、髪が非表示にならない

### ISSUE THREAD

**Issue by m-hayabusa** [yoship1639/Player2VRM#10]
キャラクター作成画面で左上から8つ目以降の髪型を使用したキャラクターを使用している場合に、クラフトピア側プレイヤーモデルの髪が非表示にならないようです

Craftopia バージョン20200919.0019
Player2VRM ver1.0.2

![](https://user-images.githubusercontent.com/10593623/93754343-8baf9a00-fc3c-11ea-8cd0-146db1f77d82.jpg)
![20200921182741_1](https://user-images.githubusercontent.com/10593623/93754346-8ce0c700-fc3c-11ea-8762-50761458a637.jpg)

**Comment by yoship1639** [comment]
@m-hayabusa 
issueに上げていただきありがとうございます！
かしこまりました。近いうちに対応いたします。

**Comment by yoship1639** [comment]
ver1.0.6で修正
