### ISSUE TITLE
坂道？を登るときのモーションがおかしくなる

### ISSUE THREAD

**Issue by yuzuka4573** [yoship1639/Player2VRM#12]
## [ Environment ]  
Craftopia ver 20200919.0019 Windows Edition  
Mod ver  BepInEx v5.3 / Player2VRM v1.0.3   

## [ Issue ]  
坂道を登るときに、走りモーションが、おかしい(手を胸の前にやる)  

## [ Situation ]
世界遺産のピラミッドの上を、**下から上へ走る**と、**手を胸の前に出しながら**走る  
また、発電機でも同じ現象が起こる時がある  
自然の地形では発生してないように見える  

## [ Supplement ]  
[![Image from Gyazo](https://i.gyazo.com/c14085f25f36106df7f5cfbfacbf933d.gif)](https://gyazo.com/c14085f25f36106df7f5cfbfacbf933d)

**Comment by yoship1639** [comment]
ver1.1.1にて解決済み
