### ISSUE TITLE
特定環境下のVRMモデルが白飛びする事がある

### ISSUE THREAD

**Issue by yuzuka4573** [yoship1639/Player2VRM#13]
## [ Environment ]  
Craftopia ver 20200919.0019 Windows Edition  
Mod ver  BepInEx v5.3 / Player2VRM v1.0.3   
  
## [ Issue ]  
特定環境下のVRMモデルが白飛びする事がある  
  
## [ Situation ]
**クラフト画面**と、**日中**(時間は画像参照)での下のVRMモデルが白飛びする事がある  
  
## [ Supplement ]  
クラフト画面
[![Image from Gyazo](https://i.gyazo.com/66c92538fd6414255eeee9418e7ec48a.png)](https://gyazo.com/66c92538fd6414255eeee9418e7ec48a)

日中のオーバーワールド
[![Image from Gyazo](https://i.gyazo.com/24a29ef33a7af16d8ad7099ab7f77261.jpg)](https://gyazo.com/24a29ef33a7af16d8ad7099ab7f77261)

- Unityのライティング(HDR?)のIntensityが1超えると発生する、白飛びっぽい感じもする  
-

**Comment by yoship1639** [comment]
@yuzuka4573 
こちらver1.0.4で直ったと思いますので、ご確認いただければ幸いです。

**Comment by yuzuka4573** [comment]
@yoship1639 
対応ありがとうございます！
オーバーワールドでの白飛び修正されていることを確認しました！  

クラフト画面の白飛びはまだ発生しているっぽいですが、プレイに支障はないので修正はあとでも良いかなと思いました
