### ISSUE TITLE
アンインストール方法について追記

### ISSUE THREAD

**Issue by daifuk-lana** [yoship1639/Player2VRM#21]
大福らなです。アンインストール後「Craftopia_Managedに入れるdll」で導入したdllファイルが残っていると、キャラクターの頭が非表示となってしまうようです。こちらのdllも合わせて削除することで改善することを確認しました。手順への追記を提案いたします。
![image](https://user-images.githubusercontent.com/59566441/93868754-e2cd7180-fd05-11ea-8fc2-f38c27633f11.png)

**Comment by yoship1639** [comment]
あ、確かに記載していなかったですね。追記しておきます！

**Comment by yoship1639** [comment]
@daifuk-lana 
追記しました。ご報告ありがとうございました！
