### ISSUE TITLE
各種ファイルの配置位置について

### ISSUE THREAD

**Issue by mituha** [yoship1639/Player2VRM#36]
現状、配布ファイルの配置が、
```
Craftopia
- Craftopia_Data
    - Managed
        + VRM.dll 等
- Player2VRM
    + player.vrm 等
- BepInEx
    - plugins
        - Player2VRM
            + Player2VRM.dll 等
```
と３箇所に分かれています。  

1. Craftopia/Player2VRM フォルダーに設定系を配置している意図は？
    + shaderのように Player2VRM.dllと同位置でも良いのでは？
2. VRM.dll 等はPlayer2VRM.dll と同階層の配置でも良いと思われます。
    + Managedへの配置は意図せず他のファイルを削除したりオリジナル環境を壊す可能性をはらんでいます。
    + もっとも、同階層配置の場合、BepInExによる処理が入るため、何か問題があるかもしれません。
    + なお、OVRLipSync.dll は同階層配置ではBepInExで処理できずエラーとなるようでした。

のように、配置が複雑になっているのが気になりました。

**Comment by yoship1639** [comment]
@mituha 
> Craftopia/Player2VRM フォルダーに設定系を配置している意図は？

設定ファイルはBepInEx/plugins内に配置しても良かったのですが、plugin階層に設定ファイルがあるのも違うと思ったので分けました。他のプラグインを私は使っていないのでどの配置が正しいかは存じ上げません。

> VRM.dll 等はPlayer2VRM.dll と同階層の配置でも良いと思われます。

同階層だとエラーを吐きます。Player2VRMはBepInExプラグインですが、VRM.dll関連はBepInExプラグインではありませんので正常にロードされません。

現在の配置は確かに複雑ですが、インストール・アンインストールのしやすさとユーザビリティの優先度とを考えたら後者の方が良いと思ったのでこの配置になっています。もっとも、今から配置を変えるのは混乱を招くのでしません。

**Comment by mituha** [comment]
回答ありがとうございます。  
実験的にVRM関連を試そうとして気になっただけです。
すでに使用ユーザー数多いと変更も難しいと思います。  

詳しくは確認していませんが、OVRLipSync.dll 以外はエラーにはならなさそうでしたので大丈夫かなと思った次第です。  

後、現状 VRM.dll 等は Unityでの環境から持ってきていると思うのですが、UnityのScripting Runtime Version 設定としては、.NET 4.x  ではない設定なのでしょうか？  
自分の環境で作成したものとは若干異なっているようでした。

ありがとうございました。
