### ISSUE TITLE
現ver.旧ver 手順通りに導入しても反映されません

### ISSUE THREAD

**Issue by Als564** [yoship1639/Player2VRM#37]
クラフトピアの再インストール後、新しいverが来ていたので導入したのですがVRMが反映されませんでした
クラフトピアをアンイストールしてやり直したり、何度か別のverで導入したのですがモデルの見た目は変わっていませんでした

**Comment by yoship1639** [comment]
@Als564 
最新のバージョンではCraftopia/Player2VRMに導入が上手くいっているかlogが出力されるようになっていますので、そのログを見ていただければと思います。

**Comment by Als564** [comment]
ログを確認したのですが、すみませんよくわかりませんでした
各、ファイルデータ名の頭にＯＫと記入されていて
文の最後にはPlayer2VRM Enabledと書かれているのですが

**Comment by yoship1639** [comment]
本来Player2VRM Enabled以降にもログが出力されるはずなので、途中でmodが効かなくなっているようです。
steamディレクトリに日本語が含まれているとmodが効かないとの報告を受けているので、お手数ですが日本語が含まれているかご確認の上、含まれている場合steam自体を日本語が含まれないディレクトリに再インストールいただけると幸いです。

**Comment by Als564** [comment]
解決しました
ありがとうございます
