### ISSUE TITLE
The mod does not work in 20201126.1951

### ISSUE THREAD

**Issue by sorat0mo** [yoship1639/Player2VRM#38]
Since the mod is updated yesterday. I suppose it is for the latest version.
Could you please add an indication as to which version this mod works for?

**Comment by yoship1639** [comment]
I neglected to check the version, sorry.

The alpha-unstable (20201127.0040~) requires VRMmod ver 1.3.7, but it seems that the stable version will not work.

If you are using the stable version (~20201126.1951), I would appreciate it if you could revert to VRMmod ver 1.3.6.
